---
title: "Explicando a votação de deputados com Regressão Linear"
author: "Valter Lucena"
date: "27 de setembro de 2018"
output: 
  html_document:
    df_print: paged
    toc: yes
    toc_float: yes
  html_notebook:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(here)
library(plotly)
theme_set(theme_minimal())
```

# le os dados

```{r}

importa_dados <- function (arquivo) {
  data = read_csv(arquivo,
                  progress = FALSE,
                  col_types = cols(ano = col_integer(),
                                   sequencial_candidato = col_character(),
                                   quantidade_doacoes = col_integer(),
                                   quantidade_doadores = col_integer(),
                                   total_receita = col_double(),
                                   media_receita = col_double(),
                                   recursos_de_outros_candidatos.comites = col_double(),
                                   recursos_de_pessoas_fisicas = col_double(),
                                   recursos_de_pessoas_juridicas = col_double(),
                                   recursos_proprios = col_double(),
                                   `recursos_de_partido_politico` = col_double(),
                                   quantidade_despesas = col_integer(),
                                   quantidade_fornecedores = col_integer(),
                                   total_despesa = col_double(),
                                   media_despesa = col_double(),
                                   votos = col_integer(),
                                   .default = col_character()))
  return(data)
}

eleicoes_2006 <- importa_dados(here("data/eleicoes_2006.csv"))
eleicoes_2010 <- importa_dados(here("data/eleicoes_2010.csv"))
eleicoes <- importa_dados(here("data/eleicoes_2006_e_2010.csv"))
eleicoes %>% names()
```


```{r}
variaveis_numericas <- function(dados) {
  nova = dados %>% 
    select(quantidade_doacoes,
           quantidade_doadores,
           total_receita,
           media_receita,
           recursos_de_outros_candidatos.comites,
           recursos_de_pessoas_fisicas,
           recursos_de_pessoas_juridicas,
           recursos_proprios,
           recursos_de_partido_politico,
           quantidade_despesas,
           quantidade_fornecedores,
           total_despesa,
           media_despesa,
           votos)
  return(nova)
}

eleicoes_num <- variaveis_numericas(eleicoes)
eleicoes_2006_num <- variaveis_numericas(eleicoes_2006)
eleicoes_2010_num <- variaveis_numericas(eleicoes_2010)
```


# assimetria

```{r message=FALSE}
library(fBasics)
eleicoes %>%  select(doacoes = quantidade_doacoes,
         doadores = quantidade_doadores,
         receita = total_receita,
         media.rct = media_receita,
         rec.comites = recursos_de_outros_candidatos.comites,
         rec.fisica = recursos_de_pessoas_fisicas,
         rec.juridica = recursos_de_pessoas_juridicas,
         rec.proprios = recursos_proprios,
         rec.partido = recursos_de_partido_politico,
         despesas = quantidade_despesas,
         fornecedores = quantidade_fornecedores,
         total.dsp = total_despesa,
         media.dsp = media_despesa,
         votos = votos) %>%  
  gather(key = "variavel",
         value = "valor") %>% 
  ggplot(aes(x = valor)) +
  geom_histogram() +
  facet_wrap(~variavel,
             scales = "free")
```

# transformando as variaveis

```{r warning=FALSE}
eleicoes %>%  select(doacoes = quantidade_doacoes,
         doadores = quantidade_doadores,
         receita = total_receita,
         media.rct = media_receita,
         rec.comites = recursos_de_outros_candidatos.comites,
         rec.fisica = recursos_de_pessoas_fisicas,
         rec.juridica = recursos_de_pessoas_juridicas,
         rec.proprios = recursos_proprios,
         rec.partido = recursos_de_partido_politico,
         despesas = quantidade_despesas,
         fornecedores = quantidade_fornecedores,
         total.dsp = total_despesa,
         media.dsp = media_despesa,
         votos = votos) %>%  
  gather(key = "variavel",
         value = "valor") %>% 
  ggplot(aes(x = log(valor))) +
  geom_histogram(bins = 20) +
  facet_wrap(~variavel,
             scales = "free")
```

# correlacoes

```{r message=FALSE}
library(corrplot)

plota_correlograma <- function(dados, ano) {
  col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
  correlacoes <- dados %>%
  cor()
  
  return(corrplot(correlacoes, 
         method = "color", 
         col = col(200),
         type = "upper",
         number.cex = .65,
         addCoef.col = "black",
         tl.col = "black",
         diag = FALSE,
         title = paste("Eleições ", ano)))
}


plota_correlograma(eleicoes_2006 %>% 
  select(doacoes = quantidade_doacoes,
         doadores = quantidade_doadores,
         receita = total_receita,
         media.rct = media_receita,
         rec.comites = recursos_de_outros_candidatos.comites,
         rec.fisica = recursos_de_pessoas_fisicas,
         rec.juridica = recursos_de_pessoas_juridicas,
         rec.proprios = recursos_proprios,
         rec.partido = recursos_de_partido_politico,
         despesas = quantidade_despesas,
         fornecedores = quantidade_fornecedores,
         total.dsp = total_despesa,
         media.dsp = media_despesa,
         votos = votos), 2006)
```
